import { Montserrat } from "next/font/google";
import "~/styles/globals.css";
import { headers } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
       </body>
    </html>
  );
}
